const shopList = {
  food: {
    dessert: [
      { name: "노티드 바나나 돌체 카라멜 케이크", image: "dessert1", price: "29,900", },
      { name: "노티드 쇼콜라 티라미수 케이크", image: "dessert2", price: "29,900", },
      { name: "노티드 마스카포네 스트로베리 베어 케이크", image: "dessert3", price: "25,900", },
      { name: "노티드 벨기에 포콜릿 슈톨렌", image: "dessert4", price: "21,900", },
      { name: "노티드 오스트리아 클래식 슈톨렌", image: "dessert5", price: "21,900", },
      { name: "[노티드] 100% 땅콩버터 크런치 & 땅콩 말차 스프레드 (2종 택1)", image: "dessert6", price: "14,900", },
      { name: "[노티드] 팝콘 2종 (시그니처 카라멜, 딥 초콜렛)", image: "dessert7", price: "6,900", },
      { name: "노티드 구름 오란다 선물꾸러미 (12개입/24개입)", image: "dessert8", price: "11,800", },
      { name: "[NEW] 진한 초코무스의 노티드 브라운 베어 케이크", image: "dessert9", price: "25,900", },
      { name: "[노티드] 가나슈 초코무스 케이크", image: "dessert10", price: "31,900", },
      { name: "[노티드] 밀크데이지 우유무스 케이크", image: "dessert11", price: "29,000", },
      { name: "[노티드] 크림도넛 BEST 6종 (말차라떼 신규 출시)", image: "dessert12", price: "11,500", },
      { name: "[노티드] 스마일 만쥬 (슈크림)", image: "dessert13", price: "5,900", },
      { name: "[노티드] 스마일 크림빵 2종", image: "dessert14", price: "11,500", },
      { name: "[노티드] 스마일 만쥬 (우유크림)", image: "dessert15", price: "5,900", },
      { name: "노티드 시그니처 스마일 케이크", image: "dessert16", price: "27,900", },
      { name: "[노티드] 슈가베어 쿠키 선물세트", image: "dessert17", price: "25,900", },
      { name: "[노티드] 셀레브레이션 아이스크림 케이크", image: "dessert18", price: "35,900", },
      { name: "[노티드] 초코베리 팡팡 아이스크림 케이크", image: "dessert19", price: "35,900", },
      { name: "[노티드] 크림가득 스마일롤", image: "dessert20", price: "19,975", },
    ],
    candy: [
      { name: "[노티드] 슈가베어 파베 초콜릿", image: "candy1", price: "19,500", },
      { name: "[노티드] 초콜릿 봉봉 2종", image: "candy2", price: "16,900", },
    ],
    vitamin: [
      { name: "[노티드] 곡물발효 효소", image: "vitamin1", price: "27,900", },
      { name: "[노티드] 촉촉 콜라겐 앰플", image: "vitamin2", price: "36,900", },
      { name: "[노티드X네추럴라이즈] 이뮨 멀티 비타민", image: "vitamin3", price: "26,900", },
      { name: "[노티드X네추럴라이즈] 알로에 젤리", image: "vitamin4", price: "16,900", },
      { name: "[노티드X네추럴라이즈] 멀티 비타민 꾸미비타 젤리", image: "vitamin5", price: "18,900", },
      { name: "[노티드X네추럴라이즈] 비타민 C 꾸미비타 젤리", image: "vitamin6", price: "18,900", },
      { name: "[노티드X네추럴라이즈] 비타민 D 꾸미비타 젤리", image: "vitamin7", price: "18,900", },
    ],
  },
  living: {
    party: [
      { name: "[노티드] 슈가베이커리 인형 4종 + 더스트백", image: "party1", price: "23,000", },
      { name: "HBD 케이크픽", image: "party2", price: "4,500", },
      { name: "스마일 케이크 캔들", image: "party3", price: "4,800", },
    ],
    phrase: [
      { name: "[노티드] 슈가베이커리 인형 4종 + 더스트백", image: "phrase1", price: "23,000", },
      { name: "[노티드] 슈가베어 카드 파우치 키링", image: "phrase2", price: "19,000", },
      { name: "스마일 옐로우 9종 굿즈 기프트 세트", image: "phrase3", price: "120,000", },
      { name: "스마일 리걸 노트", image: "phrase4", price: "6,000", },
      { name: "크림버니 리걸 노트", image: "phrase5", price: "6,000", },
      { name: "스마일 반자동 투명 우산", image: "phrase6", price: "16,800", },
      { name: "스마일 쇼핑백", image: "phrase7", price: "1,000", },
      { name: "HBD 메시지 카드 & 데코 스티커 세트", image: "phrase8", price: "3,500", },
    ],
    beverage: [
      
    ],
    home: [
      { name: "[노티드X그로미미] 유아 흡착 식판", image: "home1", price: "15,400", },
      { name: "[노티드X그로미미] 유아 물병 원터치 빨대컵 PPSU (6종 택1)", image: "home2", price: "19,800", },
      { name: "[노티드] NEW 네추럴 도우 빕", image: "home3", price: "15,000", },
      { name: "[노티드] NEW 도우퍼피 키링 보냉백", image: "home4", price: "24,000", },
      { name: "[노티드X폴라앳홈] 베이커리 테이블 미니플레이트 세트", image: "home5", price: "32,200", },
      { name: "[노티드X그로미미] 빨대컵 2종 + 인형 선물세트", image: "home6", price: "54,900", },
      { name: "[노티드] 슈가베이커리 인형 4종 + 더스트백", image: "home7", price: "23,000", },
      { name: "[노티드] 슈가베어 카드 파우치 키링", image: "home8", price: "19,000", },
      { name: "[노티드] 슈가베어 도넛가방 키링", image: "home9", price: "12,000", },
      { name: "[노티드] 슈가베어 미니 파우치 키링", image: "home10", price: "16,000", },
      { name: "[노티드X파이렉스] 믹싱볼3P 세트", image: "home11", price: "29,900", },
      { name: "[노티드X파이렉스] 계량컵3P 세트", image: "home12", price: "36,800", },
      { name: "[노티드X펠로우] 스마일 스트로우 텀블러 16oz", image: "home13", price: "59,000", },
      { name: "스마일 인센스 스틱 & 홀더 기프트 박스", image: "home14", price: "75,800", },
      { name: "스마일 인센스 홀더", image: "home15", price: "43,000", },
      { name: "[노티드X라브아] 프래그런스 태그", image: "home16", price: "12,000", },
      { name: "[노티드X덴띠끄] 스마일 트래블키트", image: "home17", price: "9,900", },
    ],
    outdoor: [
      { name: "노티드 핫팩 기프트세트", image: "outdoor1", price: "22,900", },
      { name: "노티드 슈가베어 핫팩 150g, 10개입", image: "outdoor2", price: "9,900", },
      { name: "[노티드] 모기 기피제 (라벤더향)", image: "outdoor3", price: "12,750", },
      { name: "[노티드] 크림버니 드라이버 커버", image: "outdoor4", price: "31,000", },
      { name: "[노티드X볼빅] 러블리 슈가베어 골프공 & 볼마커 세트", image: "outdoor5", price: "32,000", },
      { name: "스마일 농구공", image: "outdoor6", price: "65,000", },
    ],
  },
};